In [37]:
# OPS 807 Optimization Final Project - Amber Yao, Melanie Parazo, Dhyan Gandhi, Alex Choy, Edith Cabrera

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as dt

# Read files into notebook
df1=pd.read_csv('metro-bike-share-trips-2019-q2.csv')
df2=pd.read_csv('metro-bike-share-trips-2019-q1.csv')
frames=[df1,df2]

In [38]:
# Concatenate dataframes together
df=pd.concat(frames)
df.reset_index(inplace=True,drop=True)
df.head()

,trip_id,duration,start_time,end_time,start_station,start_lat,start_lon,end_station,end_lat,end_lon,bike_id,plan_duration,trip_route_category,passholder_type,bike_type
0,118571839,7,2019-04-01 00:02:00,2019-04-01 00:09:00,3069,34.050880,-118.248253,3034,34.042061,-118.263382,6459,1,One Way,Walk-up,standard
1,118574695,12,2019-04-01 00:56:00,2019-04-01 01:08:00,3031,34.044701,-118.252441,4311,34.059689,-118.294662,12229,30,One Way,Monthly Pass,standard
2,118575167,12,2019-04-01 01:06:00,2019-04-01 01:18:00,3038,34.046822,-118.248352,3082,34.046520,-118.237411,6422,1,One Way,Walk-up,standard
3,118577060,48,2019-04-01 01:08:00,2019-04-01 01:56:00,3068,34.053200,-118.250954,3005,34.048500,-118.258537,12211,30,One Way,Monthly Pass,standard
4,118575166,9,2019-04-01 01:09:00,2019-04-01 01:18:00,3038,34.046822,-118.248352,3082,34.046520,-118.237411,12005,1,One Way,Walk-up,standard

In [44]:
from geopy.distance import geodesic
traveled=[]
for ind in range(len(df)):
    traveled.append(geodesic((df.start_lat[ind], df.start_lon[ind]), (df.end_lat[ind], df.end_lon[ind])).miles)
traveled

ValueError: Point coordinates must be finite. (nan, nan, 0.0) has been passed as coordinates.

In [3]:
df.to_csv('stuff.csv')

In [46]:
# Add start_t and end_t columns to dataframe
df['start_t'] = pd.to_datetime(df['start_time']).dt.time
df['end_t'] = pd.to_datetime(df['end_time']).dt.time

In [47]:
df.dtypes

trip_id                  int64
duration                 int64
start_time              object
end_time                object
start_station            int64
start_lat              float64
start_lon              float64
end_station              int64
end_lat                float64
end_lon                float64
bike_id                 object
plan_duration            int64
trip_route_category     object
passholder_type         object
bike_type               object
start_t                 object
end_t                   object
dtype: object

In [48]:
# Station numbers from the Metro website
# 4125
# 4126
# 4127
# 4129
# 4130
# 4131
# 4132
# 4133
# 4134
# 4135
# 4136

In [49]:
df['start_hours'] = df.start_t.apply(lambda x: x.hour)
df.groupby('start_hours').size().to_csv('start_hours.csv')

/Applications/anaconda3/envs/optimization/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.

In [50]:
df['end_hours'] = df.end_t.apply(lambda x: x.hour)
df.groupby('end_hours').size().to_csv('end_hours.csv')

/Applications/anaconda3/envs/optimization/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.

In [51]:
longbeach=df[df['end_station'].isin([4125, 4126, 4127, 4129, 4130, 4131, 4132, 4133, 4134, 4135, 4136]) & df['start_station'].isin([4125, 4126, 4127, 4129, 4130, 4131, 4132, 4133, 4134, 4135, 4136, 4435])]

longbeach.groupby('start_station').size().to_csv('start_station.csv')

/Applications/anaconda3/envs/optimization/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  This is separate from the ipykernel package so we can avoid doing imports until

In [52]:
longbeach.groupby('end_station').size().to_csv('end_station.csv')

/Applications/anaconda3/envs/optimization/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """Entry point for launching an IPython kernel.

In [53]:
longbeach.start_t.max()

datetime.time(23, 48)

In [54]:
longbeach.start_t.min()

datetime.time(0, 13)

In [57]:
longbeach.reset_index(inplace=True, drop=True)

In [59]:
longbeach

,trip_id,duration,start_time,end_time,start_station,start_lat,start_lon,end_station,end_lat,end_lon,bike_id,plan_duration,trip_route_category,passholder_type,bike_type,start_t,end_t,start_hours,end_hours
0,118596824,30,2019-04-01 08:29:00,2019-04-01 08:59:00,4129,33.725819,-118.280510,4129,33.725819,-118.280510,11981,1,Round Trip,Walk-up,standard,08:29:00,08:59:00,8,8
1,118602482,47,2019-04-01 10:18:00,2019-04-01 11:05:00,4132,33.749130,-118.280182,4132,33.749130,-118.280182,5006,1,Round Trip,Walk-up,standard,10:18:00,11:05:00,10,11
2,118613476,26,2019-04-01 14:38:00,2019-04-01 15:04:00,4130,33.719261,-118.282722,4130,33.719261,-118.282722,12284,1,Round Trip,Walk-up,standard,14:38:00,15:04:00,14,15
3,118616385,87,2019-04-01 14:40:00,2019-04-01 16:07:00,4130,33.719261,-118.282722,4130,33.719261,-118.282722,6402,1,Round Trip,Walk-up,standard,14:40:00,16:07:00,14,16
4,118613468,21,2019-04-01 14:43:00,2019-04-01 15:04:00,4130,33.719261,-118.282722,4130,33.719261,-118.282722,12441,1,Round Trip,Walk-up,standard,14:43:00,15:04:00,14,15
5,118702726,1259,2019-04-01 15:51:00,2019-04-02 12:50:00,4133,33.733521,-118.277786,4133,33.733521,-118.277786,5744,1,Round Trip,Walk-up,standard,15:51:00,12:50:00,15,12
6,118616765,13,2019-04-01 16:07:00,2019-04-01 16:20:00,4134,33.741360,-118.278069,4134,33.741360,-118.278069,6714,1,Round Trip,Walk-up,standard,16:07:00,16:20:00,16,16
7,118616763,13,2019-04-01 16:08:00,2019-04-01 16:21:00,4134,33.741360,-118.278069,4134,33.741360,-118.278069,12285,1,Round Trip,Walk-up,standard,16:08:00,16:21:00,16,16
8,118617905,25,2019-04-01 16:18:00,2019-04-01 16:43:00,4134,33.741360,-118.278069,4130,33.719261,-118.282722,5723,1,One Way,Walk-up,standard,16:18:00,16:43:00,16,16
9,118617904,24,2019-04-01 16:19:00,2019-04-01 16:43:00,4134,33.741360,-118.278069,4130,33.719261,-118.282722,6355,1,One Way,Walk-up,standard,16:19:00,16:43:00,16,16
10,118621747,16,2019-04-01 17:49:00,2019-04-01 18:05:00,4129,33.725819,-118.280510,4129,33.725819,-118.280510,6289,30,Round Trip,Monthly Pass,standard,17:49:00,18:05:00,17,18
11,118623572,24,2019-04-01 18:25:00,2019-04-01 18:49:00,4130,33.719261,-118.282722,4130,33.719261,-118.282722,12175,1,Round Trip,Walk-up,standard,18:25:00,18:49:00,18,18
12,118623573,24,2019-04-01 18:25:00,2019-04-01 18:49:00,4130,33.719261,-118.282722,4130,33.719261,-118.282722,12353,1,Round Trip,Walk-up,standard,18:25:00,18:49:00,18,18
13,118627487,28,2019-04-01 19:42:00,2019-04-01 20:10:00,4126,33.710979,-118.284668,4126,33.710979,-118.284668,5027,1,Round Trip,Walk-up,standard,19:42:00,20:10:00,19,20
14,118675814,100,2019-04-02 11:01:00,2019-04-02 12:41:00,4132,33.749130,-118.280182,4132,33.749130,-118.280182,12009,1,Round Trip,Walk-up,standard,11:01:00,12:41:00,11,12
15,118675806,94,2019-04-02 11:07:00,2019-04-02 12:41:00,4132,33.749130,-118.280182,4132,33.749130,-118.280182,5006,1,Round Trip,Walk-up,standard,11:07:00,12:41:00,11,12
16,118677107,12,2019-04-02 13:03:00,2019-04-02 13:15:00,4131,33.738979,-118.279266,4132,33.749130,-118.280182,6051,1,One Way,Walk-up,standard,13:03:00,13:15:00,13,13
17,118770880,912,2019-04-02 14:37:00,2019-04-03 05:49:00,4132,33.749130,-118.280182,4132,33.749130,-118.280182,12159,1,Round Trip,Walk-up,standard,14:37:00,05:49:00,14,5
18,118682460,30,2019-04-02 14:38:00,2019-04-02 15:08:00,4132,33.749130,-118.280182,4132,33.749130,-118.280182,6051,1,Round Trip,Walk-up,standard,14:38:00,15:08:00,14,15
19,118689382,33,2019-04-02 17:11:00,2019-04-02 17:44:00,4131,33.738979,-118.279266,4132,33.749130,-118.280182,12041,1,One Way,Walk-up,standard,17:11:00,17:44:00,17,17
20,118689377,32,2019-04-02 17:12:00,2019-04-02 17:44:00,4131,33.738979,-118.279266,4132,33.749130,-118.280182,6020,1,One Way,Walk-up,standard,17:12:00,17:44:00,17,17
21,118753838,34,2019-04-03 15:41:00,2019-04-03 16:15:00,4126,33.710979,-118.284668,4126,33.710979,-118.284668,6682,1,Round Trip,Walk-up,standard,15:41:00,16:15:00,15,16
22,118753834,33,2019-04-03 15:42:00,2019-04-03 16:15:00,4126,33.710979,-118.284668,4126,33.710979,-118.284668,12173,1,Round Trip,Walk-up,standard,15:42:00,16:15:00,15,16
23,118753828,31,2019-04-03 15:46:00,2019-04-03 16:17:00,4126,33.710979,-118.284668,4126,33.710979,-118.284668,6271,1,Round Trip,Walk-up,standard,15:46:00,16:17:00,15,16
24,118753826,28,2019-04-03 15:47:00,2019-04-03 16:15:00,4126,33.710979,-118.284668,4126,33.710979,-118.284668,12180,1,Round Trip,Walk-up,standard,15:47:00,16:15:00,15,16
25,118753823,26,2019-04-03 15:50:00,2019-04-03 16:16:00,4126,33.710979,-118.284668,4126,33.710979,-118.284668,12201,1,Round Trip,Walk-up,standard,15:50:00,16:16:00,15,16
26,118755572,56,2019-04-03 16:03:00,2019-04-03 16:59:00,4126,33.710979,-118.284668,4126,33.710979,-118.284668,12205,1,Round Trip,Walk-up,standard,16:03:00,16:59:00,16,16
27,118755568,54,2019-04-03 16:05:00,2019-04-03 16:59:00,4126,33.710979,-118.284668,4126,33.710979,-118.284668,5027,1,Round Trip,Walk-up,standard,16:05:00,16:59:00,16,16
28,118907425,1440,2019-04-03 19:51:00,2019-04-05 14:06:00,4127,33.748920,-118.275192,4127,33.748920,-118.275192,6235,1,Round Trip,Walk-up,standard,19:51:00,14:06:00,19,14
29,118765039,36,2019-04-03 19:52:00,2019-04-03 20:28:00,4127,33.748920,-118.275192,4127,33.748920,-118.275192,12291,1,Round Trip,Walk-up,standard,19:52:00,20:28:00,19,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2864,118540263,28,2019-03-31 12:15:00,2019-03-31 12:43:00,4127,33.748920,-118.275192,4130,33.719261,-118.282722,06574,1,One Way,Walk-up,standard,12:15:00,12:43:00,12,12
2865,118540496,31,2019-03-31 12:16:00,2019-03-31 12:47:00,4127,33.748920,-118.275192,4130,33.719261,-118.282722,12175,1,One Way,Walk-up,standard,12:16:00,12:47:00,12,12
2866,118540492,27,2019-03-31 12:20:00,2019-03-31 12:47:00,4127,33.748920,-118.275192,4130,33.719261,-118.282722,12164,1,One Way,Walk-up,standard,12:20:00,12:47:00,12,12
2867,118542488,17,2019-03-31 13:14:00,2019-03-31 13:31:00,4131,33.738979,-118.279266,4129,33.725819,-118.280510,06020,1,One Way,Walk-up,standard,13:14:00,13:31:00,13,13
2868,118542487,17,2019-03-31 13:15:00,2019-03-31 13:32:00,4131,33.738979,-118.279266,4129,33.725819,-118.280510,05753,1,One Way,Walk-up,standard,13:15:00,13:32:00,13,13
2869,118543382,33,2019-03-31 13:20:00,2019-03-31 13:53:00,4131,33.738979,-118.279266,4131,33.738979,-118.279266,12176,1,Round Trip,Walk-up,standard,13:20:00,13:53:00,13,13
2870,118549987,182,2019-03-31 13:20:00,2019-03-31 16:22:00,4129,33.725819,-118.280510,4129,33.725819,-118.280510,12016,1,Round Trip,Walk-up,standard,13:20:00,16:22:00,13,16
2871,118703754,1440,2019-03-31 13:20:00,2019-04-02 05:45:00,4129,33.725819,-118.280510,4129,33.725819,-118.280510,06130,1,Round Trip,Walk-up,standard,13:20:00,05:45:00,13,5
2872,118543381,32,2019-03-31 13:21:00,2019-03-31 13:53:00,4131,33.738979,-118.279266,4131,33.738979,-118.279266,06489,1,Round Trip,Walk-up,standard,13:21:00,13:53:00,13,13
2873,118543375,30,2019-03-31 13:25:00,2019-03-31 13:55:00,4133,33.733521,-118.277786,4134,33.741360,-118.278069,06714,1,One Way,Walk-up,standard,13:25:00,13:55:00,13,13
2874,118544285,49,2019-03-31 13:25:00,2019-03-31 14:14:00,4129,33.725819,-118.280510,4129,33.725819,-118.280510,06225,1,Round Trip,Walk-up,standard,13:25:00,14:14:00,13,14
2875,118543374,29,2019-03-31 13:26:00,2019-03-31 13:55:00,4133,33.733521,-118.277786,4134,33.741360,-118.278069,06051,1,One Way,Walk-up,standard,13:26:00,13:55:00,13,13
2876,118550175,155,2019-03-31 13:52:00,2019-03-31 16:27:00,4132,33.749130,-118.280182,4132,33.749130,-118.280182,06504,1,Round Trip,Walk-up,standard,13:52:00,16:27:00,13,16
2877,118544481,12,2019-03-31 14:06:00,2019-03-31 14:18:00,4130,33.719261,-118.282722,4130,33.719261,-118.282722,06402,1,Round Trip,Walk-up,standard,14:06:00,14:18:00,14,14
2878,118547082,51,2019-03-31 14:29:00,2019-03-31 15:20:00,4132,33.749130,-118.280182,4132,33.749130,-118.280182,06185,1,Round Trip,Walk-up,standard,14:29:00,15:20:00,14,15
2879,118545981,7,2019-03-31 14:45:00,2019-03-31 14:52:00,4133,33.733521,-118.277786,4133,33.733521,-118.277786,06722,1,Round Trip,Walk-up,standard,14:45:00,14:52:00,14,14
2880,118545979,5,2019-03-31 14:47:00,2019-03-31 14:52:00,4133,33.733521,-118.277786,4133,33.733521,-118.277786,06663,1,Round Trip,Walk-up,standard,14:47:00,14:52:00,14,14
2881,118546620,16,2019-03-31 14:50:00,2019-03-31 15:06:00,4129,33.725819,-118.280510,4131,33.738979,-118.279266,06020,1,One Way,Walk-up,standard,14:50:00,15:06:00,14,15
2882,118546621,16,2019-03-31 14:50:00,2019-03-31 15:06:00,4129,33.725819,-118.280510,4131,33.738979,-118.279266,05753,1,One Way,Walk-up,standard,14:50:00,15:06:00,14,15
2883,118549838,9,2019-03-31 16:12:00,2019-03-31 16:21:00,4134,33.741360,-118.278069,4133,33.733521,-118.277786,06623,1,One Way,Walk-up,standard,16:12:00,16:21:00,16,16
2884,118549837,7,2019-03-31 16:13:00,2019-03-31 16:20:00,4134,33.741360,-118.278069,4133,33.733521,-118.277786,06355,1,One Way,Walk-up,standard,16:13:00,16:20:00,16,16
2885,118552907,66,2019-03-31 16:27:00,2019-03-31 17:33:00,4132,33.749130,-118.280182,4132,33.749130,-118.280182,05006,1,Round Trip,Walk-up,standard,16:27:00,17:33:00,16,17
2886,118552647,10,2019-03-31 17:15:00,2019-03-31 17:25:00,4134,33.741360,-118.278069,4131,33.738979,-118.279266,06051,1,One Way,Walk-up,standard,17:15:00,17:25:00,17,17
2887,118552648,10,2019-03-31 17:15:00,2019-03-31 17:25:00,4134,33.741360,-118.278069,4131,33.738979,-118.279266,12041,1,One Way,Walk-up,standard,17:15:00,17:25:00,17,17
2888,118552642,4,2019-03-31 17:21:00,2019-03-31 17:25:00,4134,33.741360,-118.278069,4131,33.738979,-118.279266,12430,1,One Way,Walk-up,standard,17:21:00,17:25:00,17,17
2889,118552643,4,2019-03-31 17:21:00,2019-03-31 17:25:00,4134,33.741360,-118.278069,4131,33.738979,-118.279266,12440,1,One Way,Walk-up,standard,17:21:00,17:25:00,17,17
2890,118557329,54,2019-03-31 18:22:00,2019-03-31 19:16:00,4132,33.749130,-118.280182,4132,33.749130,-118.280182,05006,1,Round Trip,Walk-up,standard,18:22:00,19:16:00,18,19
2891,118557537,33,2019-03-31 18:48:00,2019-03-31 19:21:00,4132,33.749130,-118.280182,4132,33.749130,-118.280182,12009,365,Round Trip,Walk-up,standard,18:48:00,19:21:00,18,19
2892,118557524,21,2019-03-31 19:00:00,2019-03-31 19:21:00,4132,33.749130,-118.280182,4132,33.749130,-118.280182,06504,365,Round Trip,Walk-up,standard,19:00:00,19:21:00,19,19
2893,118561273,30,2019-03-31 20:15:00,2019-03-31 20:45:00,4129,33.725819,-118.280510,4129,33.725819,-118.280510,11981,1,Round Trip,Walk-up,standard,20:15:00,20:45:00,20,20

In [63]:
from geopy.distance import geodesic
import math
traveled=[]
for ind in range(len(longbeach)):
    traveled.append(geodesic((longbeach.start_lat[ind], longbeach.start_lon[ind]), (longbeach.end_lat[ind], longbeach.end_lon[ind])).miles)
np.mean(traveled)

0.19874875470448183

In [27]:
# Choose a time period 8 am - 9 am
morningout=longbeach.loc[longbeach['start_t'].between(dt.time(8,0), dt.time(9,0))]

In [31]:
# Count the number of trips that leave from each station 
m_out=morningout.groupby('start_station').count()['trip_id']
m_out.to_csv('m_out.csv')

/Applications/anaconda3/envs/optimization/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  This is separate from the ipykernel package so we can avoid doing imports until

In [29]:
# Choose a time period 8 am to 9 am 
morningin=longbeach.loc[longbeach['end_t'].between(dt.time(8,0), dt.time(9,0))]

In [32]:
# Count the number of trips that come in at each station
m_in=morningin.groupby('end_station').count()['trip_id']
m_in.to_csv('m_in.csv')

/Applications/anaconda3/envs/optimization/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  This is separate from the ipykernel package so we can avoid doing imports until

In [13]:
# Numnber of bikes leaving minus number of bikes coming in
# If the result is negative, that means more bikes are coming in than leaving
# We want to look at the positive numbers because that's the demand at the station

demandmorn=m_out-m_in 
demandmorn

4126    -2.0
4127     NaN
4129     4.0
4130    15.0
4131     4.0
4132    -2.0
4133     4.0
4134     5.0
4135     1.0
Name: trip_id, dtype: float64

In [33]:
# Choose a time period 7 pm to 8 pm
nightin=longbeach.loc[longbeach['end_t'].between(dt.time(19,0), dt.time(20,0))]

In [34]:
# Count the number of bikes that come in at each station
n_in=nightin.groupby('end_station').count()['trip_id']
n_in.to_csv('n_in.csv')

/Applications/anaconda3/envs/optimization/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  This is separate from the ipykernel package so we can avoid doing imports until

In [35]:
# Choose a time period 7 pm to 8 pm
nightout=longbeach.loc[longbeach['start_t'].between(dt.time(19,0), dt.time(20,0))]

In [36]:
# Count the number of bikes that leave each station
n_out=nightout.groupby('start_station').count()['trip_id']
n_out.to_csv('n_out.csv')

/Applications/anaconda3/envs/optimization/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  This is separate from the ipykernel package so we can avoid doing imports until

In [18]:
# Number of bikes leaving minus number of bikes coming in
# If the result is negative, that means more bikes are coming in than leaving
# We want to look at the negative numbers because that's the excess bikes where our supply will come from
demandnight=n_out-n_in 
demandnight

start_station
4125    -6
4126     7
4127     3
4129   -10
4130     1
4131    -5
4132    10
4133   -11
4134     0
4135     1
4136    -4
Name: trip_id, dtype: int64

In [19]:
# Calculate distance between stations
from geopy.distance import great_circle
from geopy.distance import vincenty

In [20]:
# Data is from JSON file from the Metro website
data = {'station_id':[4125,4126,4127,4129,4130,4131,4132,4133,4134,4135,4136],
        'lat':[33.76666,33.71098,33.74892,33.72582,33.71926,33.73898,33.74913,33.73352,33.74136,33.7723,33.77176], 
        'lon':[-118.26102,-118.28467, -118.27519,-118.28051,-118.28272,-118.27927,-118.28018,-118.27779,-118.27807,-118.26804,-118.27654]} 
  
# Create DataFrame 
station = pd.DataFrame(data)

In [21]:
# Join latitude and longitude into another column
station['coords'] = tuple(zip(station.lat, station.lon))

In [22]:
# Creates a "square" dataframe
square = pd.DataFrame(
    np.zeros(len(station) ** 2).reshape(len(station), len(station)),
    index=station.index, columns=station.index)

# Applies Geopy Vicenty function to each row, left to right
def get_distance(col):
    end = station.iloc[col.name]['coords']
    return station['coords'].apply(vincenty, args=(end,), ellipsoid='WGS-84')

In [23]:
distances = square.apply(get_distance, axis=1).T
distances

,0,1,2,3,4,5,6,7,8,9,10
0,0.0 km,6.553216640514692 km,2.3654218773372397 km,4.876594676222695 km,5.628899416257218 km,3.505037546911986 km,2.63280042388434 km,3.9907371892369916 km,3.220295531572122 km,0.9023431060805943 km,1.5449643189172177 km
1,6.553216640514959 km,0.0 km,4.298944165210746 km,1.6905719764630582 km,0.9360125296102768 km,3.145755546335409 km,4.251914001394626 km,2.5801181782167366 km,3.4247414178832045 km,6.973860288764218 km,6.78354162233693 km
2,2.365421877337352 km,4.298944165210733 km,0.0 km,2.609195431398194 km,3.3630101455090258 km,1.1655399264255264 km,0.462937782315351 km,1.7250401470612797 km,0.8799779292548512 km,2.676526149496487 km,2.5364539439300353 km
3,4.876594676222524 km,1.6905719764628664 km,2.6091954313980565 km,0.0 km,0.7558995168183865 km,1.4641915586372174 km,2.5856713379239578 km,0.8904891932624012 km,1.738427885096244 km,5.283348731295185 km,5.108826218716422 km
4,5.628899416256943 km,0.9360125296105709 km,3.3630101455089196 km,0.7558995168184874 km,0.0 km,2.2105389005490994 km,3.3214597119072593 km,1.6463564010263316 km,2.4888695055773615 km,6.038283963975098 km,5.851272263385747 km
5,3.5050375469115758 km,3.145755546335022 km,1.1655399264253472 km,1.464191558637032 km,2.21053890054939 km,0.0 km,1.1289687247063969 km,0.6209461207122363 km,0.28644833322279234 km,3.839448223305313 km,3.64467820012752 km
6,2.632800423884295 km,4.251914001394641 km,0.46293778231535054 km,2.585671337924117 km,3.321459711906881 km,1.128968724706582 km,0.0 km,1.745532083901112 km,0.8837295984088368 km,2.805293888307772 km,2.5326269358089673 km
7,3.990737189236951 km,2.580118178217 km,1.7250401470612593 km,0.8904891932620734 km,1.6463564010264524 km,0.6209461207122545 km,1.7455320839008064 km,0.0 km,0.8699814154719752 km,4.39523182572274 km,4.243082364610316 km
8,3.220295531571789 km,3.4247414178831534 km,0.8799779292547572 km,1.7384278850961956 km,2.4888695055776022 km,0.28644833322300783 km,0.8837295984089575 km,0.8699814154719893 km,0.0 km,3.5553874273474793 km,3.374885290926732 km
9,0.9023431060806035 km,6.973860288763894 km,2.6765261494965875 km,5.283348731295197 km,6.03828396397519 km,3.8394482233054443 km,2.805293888307989 km,4.395231825722985 km,3.5553874273475152 km,0.0 km,0.7896370953911429 km
10,1.5449643189171969 km,6.783541622337038 km,2.536453943930383 km,5.108826218716319 km,5.851272263385825 km,3.6446782001275215 km,2.532626935808944 km,4.243082364610769 km,3.3748852909266347 km,0.7896370953911267 km,0.0 km

In [24]:
# Converts units to miles
def units(input_instance):
    return input_instance.miles

station_miles = distances.applymap(units)
station_miles

,0,1,2,3,4,5,6,7,8,9,10
0,0.000000,4.071980,1.469805,3.030175,3.497636,2.177929,1.635946,2.479729,2.000999,0.560690,0.959996
1,4.071980,0.000000,2.671240,1.050473,0.581611,1.954682,2.642017,1.603211,2.128036,4.333356,4.215097
2,1.469805,2.671240,0.000000,1.621279,2.089678,0.724233,0.287656,1.071890,0.546793,1.663116,1.576079
3,3.030175,1.050473,1.621279,0.000000,0.469694,0.909806,1.606662,0.553324,1.080209,3.282921,3.174477
4,3.497636,0.581611,2.089678,0.469694,0.000000,1.373565,2.063859,1.022998,1.546512,3.752016,3.635812
5,2.177929,1.954682,0.724233,0.909806,1.373565,0.000000,0.701509,0.385838,0.177991,2.385723,2.264698
6,1.635946,2.642017,0.287656,1.606662,2.063859,0.701509,0.000000,1.084623,0.549124,1.743129,1.573701
7,2.479729,1.603211,1.071890,0.553324,1.022998,0.385838,1.084623,0.000000,0.540581,2.731070,2.636529
8,2.000999,2.128036,0.546793,1.080209,1.546512,0.177991,0.549124,0.540581,0.000000,2.209215,2.097056
9,0.560690,4.333356,1.663116,3.282921,3.752016,2.385723,1.743129,2.731070,2.209215,0.000000,0.490658
10,0.959996,4.215097,1.576079,3.174477,3.635812,2.264698,1.573701,2.636529,2.097056,0.490658,0.000000

In [25]:
# Adds up the distances between each station to every other stations together
station_miles.sum().sum()

197.37727250939895

In [26]:
# Calculate the distances from each of our chosen supply and demand stations
distance = {'start':[0,0,0,0,3,3,3,3,5,5,5,5,7,7,7,7,10,10,10,10],
        'stop':[2,4,8,9,2,4,8,9,2,4,8,9,2,4,8,9,2,4,8,9]}
distance = pd.DataFrame(distance)

In [27]:
# Goes through the combinations to calculate distance bewteen chosen points
dist=[]
for i in range(len(distance)):
    dist.append(station_miles.loc[distance['start'].iloc[i],distance['stop'].iloc[i]])

In [28]:
# Adds a distance column to the start/stop dataframe 
distance['dist']=dist
distance

    start  stop      dist
0       0     2  1.469805
1       0     4  3.497636
2       0     8  2.000999
3       0     9  0.560690
4       3     2  1.621279
5       3     4  0.469694
6       3     8  1.080209
7       3     9  3.282921
8       5     2  0.724233
9       5     4  1.373565
10      5     8  0.177991
11      5     9  2.385723
12      7     2  1.071890
13      7     4  1.022998
14      7     8  0.540581
15      7     9  2.731070
16     10     2  1.576079
17     10     4  3.635812
18     10     8  2.097056
19     10     9  0.490658

Let $X_{ij}$ = number of bikes transported from i station to j station  
where  
$i = 1, 2, 3, 4, 5$, with 1 = 4125, 2 = 4129, 3 = 4131, 4 = 4133, 5 = 4136  
$j = 1, 2, 3, 4$, with 1 = 4127, 2 = 4130, 3 = 4134, 4 = 4135  

Minimize cost = $ \$ 0.58(1.5X_{11} + 3.5X_{12} + 2X_{13} + .6X_{14} + 1.6X_{21} + .5X_{22} + 1.1X_{23} + 3.3X_{24} + .7X_{31} + 1.4X_{32} + .2X_{33} + 2.4X_{34} + 1.1X_{41} + 1X_{42} + .5X_{43} + 2.7X_{44} + 1.6X_{51} + 3.6X_{52} + 2.1X_{53} + .5X_{54})$

Subject to:  
$X_{11} + X_{12} + X_{13} + X_{14} \leq 6$ (4125 supply)    
$X_{21} + X_{22} + X_{23} + X_{24} \leq 6$ (4129 supply)    
$X_{31} + X_{32} + X_{33} + X_{34} \leq 1$ (4131 supply)    
$X_{41} + X_{42} + X_{43} + X_{44} \leq 7$ (4133 supply)    
$X_{51} + X_{52} + X_{53} + X_{54} \leq 4$ (4136 supply)    
$X_{11} + X_{21} + X_{31} + X_{41} + X_{51} = 2$ (4127 demand)  
$X_{12} + X_{22} + X_{32} + X_{42} + X_{52} = 15$ (4130 demand)  
$X_{13} + X_{23} + X_{33} + X_{43} + X_{53} = 5$ (4134 demand)  
$X_{14} + X_{24} + X_{34} + X_{44} + X_{54} = 1$ (4135 demand)  
$X_{ij} \geq 0$, integer

In [33]:
from pulp import *

In [34]:
# Create model
model = LpProblem("Cost minimising problem", LpMinimize)

# Variables
x11 = LpVariable('x11', lowBound=0, cat='Integer')
x12 = LpVariable('x12', lowBound=0, cat='Integer')
x13 = LpVariable('x13', lowBound=0, cat='Integer')
x14 = LpVariable('x14', lowBound=0, cat='Integer')
x21 = LpVariable('x21', lowBound=0, cat='Integer')
x22 = LpVariable('x22', lowBound=0, cat='Integer')
x23 = LpVariable('x23', lowBound=0, cat='Integer')
x24 = LpVariable('x24', lowBound=0, cat='Integer')
x31 = LpVariable('x31', lowBound=0, cat='Integer')
x32 = LpVariable('x32', lowBound=0, cat='Integer')
x33 = LpVariable('x33', lowBound=0, cat='Integer')
x34 = LpVariable('x34', lowBound=0, cat='Integer')
x41 = LpVariable('x41', lowBound=0, cat='Integer')
x42 = LpVariable('x42', lowBound=0, cat='Integer')
x43 = LpVariable('x43', lowBound=0, cat='Integer')
x44 = LpVariable('x44', lowBound=0, cat='Integer')
x51 = LpVariable('x51', lowBound=0, cat='Integer')
x52 = LpVariable('x52', lowBound=0, cat='Integer')
x53 = LpVariable('x53', lowBound=0, cat='Integer')
x54 = LpVariable('x54', lowBound=0, cat='Integer')

y11 = LpVariable('y11', lowBound=0, cat='Binary')
y12 = LpVariable('y12', lowBound=0, cat='Binary')
y13 = LpVariable('y13', lowBound=0, cat='Binary')
y14 = LpVariable('y14', lowBound=0, cat='Binary')
y21 = LpVariable('y21', lowBound=0, cat='Binary')
y22 = LpVariable('y22', lowBound=0, cat='Binary')
y23 = LpVariable('y23', lowBound=0, cat='Binary')
y24 = LpVariable('y24', lowBound=0, cat='Binary')
y31 = LpVariable('y31', lowBound=0, cat='Binary')
y32 = LpVariable('y32', lowBound=0, cat='Binary')
y33 = LpVariable('y33', lowBound=0, cat='Binary')
y34 = LpVariable('y34', lowBound=0, cat='Binary')
y41 = LpVariable('y41', lowBound=0, cat='Binary')
y42 = LpVariable('y42', lowBound=0, cat='Binary')
y43 = LpVariable('y43', lowBound=0, cat='Binary')
y44 = LpVariable('y44', lowBound=0, cat='Binary')
y51 = LpVariable('y51', lowBound=0, cat='Binary')
y52 = LpVariable('y52', lowBound=0, cat='Binary')
y53 = LpVariable('y53', lowBound=0, cat='Binary')
y54 = LpVariable('y54', lowBound=0, cat='Binary')


#objective function
model += 0.58*(1.5*y11 + 3.5*y12 + 2*y13 + .6*y14 + 1.6*y21 + .5*y22 + 1.1*y23 + 3.3*y24 + .7*y31 + 1.4*y32 + .2*y33 + 2.4*y34 + 1.1*y41 + 1*y42 + .5*y43 + 2.7*y44 + 1.6*y51 + 3.6*y52 + 2.1*y53 + .5*y54), "Cost"


# Constraints
model += y11*x11 + y12*x12 + y13*x13 + y14*x14 <= 6 #(4125 supply)    
model += y21*x21 + y22*x22 + y23*x23 + y24*x24 <= 6 #(4129 supply)    
model += y31*x31 + y32*x32 + y33*x33 + y34*x34 <= 6 #(4131 supply)    
model += y41*x41 + y42*x42 + y43*x43 + y44*x44 <= 6 #(4133 supply)    
model += y51*x51 + y52*x52 + y53*x53 + y54*x54 <= 6 #(4136 supply)    
model += y11*x11 + y21*x21 + y31*x31 + y41*x41 + y51*x51 == 2 #(4127 demand)  
model += y12*x12 + y22*x22 + y32*x32 + y42*x42 + y52*x52 == 15 #(4130 demand)  
model += y13*x13 + y23*x23 + y33*x33 + y43*x43 + y53*x53 == 5 #(4134 demand)  
model += y14*x14 + y24*x24 + y34*x34 + y44*x44 + y54*x54 == 1 #(4135 demand)

# Solve our problem
model.solve()
LpStatus[model.status]

TypeError: Non-constant expressions cannot be multiplied

In [31]:
# Print least cost to move bikes around 
print(f'Total cost is = ${value(model.objective)}')

Total cost is = $12.354

In [32]:
# Print the number of bikes that need to be moved from one station to the other
print(f'Number of bikes moved from 4125 to 4127: {x11.varValue},\nNumber of bikes moved from 4125 to 4130: {x12.varValue}, \nNumber of bikes moved from 4125 to 4134: {x13.varValue}, \nNumber of bikes moved from 4125 to 4135: {x14.varValue},\nNumber of bikes moved from 4129 to 4127: {x21.varValue}, \nNumber of bikes moved from 4129 to 4130: {x22.varValue}, \nNumber of bikes moved from 4129 to 4134: {x23.varValue}, \nNumber of bikes moved from 4129 to 4135: {x24.varValue}, \nNumber of bikes moved from 4131 to 4127: {x31.varValue}, \nNumber of bikes moved from 4131 to 4130: {x32.varValue}, \nNumber of bikes moved from 4131 to 4134: {x33.varValue}, \nNumber of bikes moved from 4131 to 4135: {x34.varValue}, \nNumber of bikes moved from 4133 to 4127: {x41.varValue}, \nNumber of bikes moved from 4133 to 4130: {x42.varValue}, \nNumber of bikes moved from 4133 to 4134: {x43.varValue}, \nNumber of bikes moved from 4133 to 4135: {x44.varValue}, \nNumber of bikes moved from 4136 to 4127: {x51.varValue}, \nNumber of bikes moved from 4136 to 4130: {x52.varValue}, \nNumber of bikes moved from 4136 to 4134: {x53.varValue},\nNumber of bikes moved from 4136 to 4135: {x54.varValue}')

Number of bikes moved from 4125 to 4127: 2.0,
Number of bikes moved from 4125 to 4130: 0.0,
Number of bikes moved from 4125 to 4134: 2.0,
Number of bikes moved from 4125 to 4135: 0.0,
Number of bikes moved from 4129 to 4127: 0.0,
Number of bikes moved from 4129 to 4130: 6.0,
Number of bikes moved from 4129 to 4134: 0.0,
Number of bikes moved from 4129 to 4135: 0.0,
Number of bikes moved from 4131 to 4127: 0.0,
Number of bikes moved from 4131 to 4130: 3.0,
Number of bikes moved from 4131 to 4134: 3.0,
Number of bikes moved from 4131 to 4135: 0.0,
Number of bikes moved from 4133 to 4127: 0.0,
Number of bikes moved from 4133 to 4130: 6.0,
Number of bikes moved from 4133 to 4134: 0.0,
Number of bikes moved from 4133 to 4135: 0.0,
Number of bikes moved from 4136 to 4127: 0.0,
Number of bikes moved from 4136 to 4130: 0.0,
Number of bikes moved from 4136 to 4134: 0.0,
Number of bikes moved from 4136 to 4135: 1.0